export const getEnvVariables = () => {
    return {
        NEXT_PUBLIC_PORT_LOCAL: process.env.NEXT_PUBLIC_PORT_LOCAL,
        /* VARIABLE DE ENTORNO PARA EL MICROSERVICIO  DESARROLLO */
        NEXT_PUBLIC_ENV_MS_BUSINESS_API_URL_DESARROLLO: process.env.NEXT_PUBLIC_ENV_MS_BUSINESS_API_URL_DESARROLLO,
        NEXT_PUBLIC_ENV_MS_SECURITY_API_URL_DESARROLLO: process.env.NEXT_PUBLIC_ENV_MS_SECURITY_API_URL_DESARROLLO,
        /* VARIABLE DE ENTORNO PARA EL MICROSERVICIO  PRODUCCION */
        NEXT_PUBLIC_ENV_MS_BUSINESS_API_URL_PRODUCCION: process.env.NEXT_PUBLIC_ENV_MS_BUSINESS_API_URL_PRODUCCION,
        NEXT_PUBLIC_ENV_MS_SECURITY_API_URL_PRODUCCION: process.env.NEXT_PUBLIC_ENV_MS_SECURITY_API_URL_PRODUCCION,
        /* ENTORNO DE DESARROLLO */
        NEXT_PUBLIC_ENTORNO: process.env.NEXT_PUBLIC_ENTORNO,
    }
}